apiVersion: v1
kind: ConfigMap
metadata:
  name: productservice-config
  namespace: vibevault
  labels:
    app: productservice
    part-of: vibevault
data:
  PORT: "8080"
  DB_URL: "jdbc:mysql://productservice-mysql:3306/productservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  ISSUER_URI: "http://userservice:8081"
  SPRING_PROFILES_ACTIVE: "default"
