apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "productservice.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "productservice.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "productservice.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecretName }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecretName }}
        property: password
