{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "productservice.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "productservice.fullname" . }}-mysql
    part-of: vibevault
spec:
  type: ClusterIP
  selector:
    app: {{ include "productservice.fullname" . }}-mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
{{- end }}
