apiVersion: v1
kind: Secret
metadata:
  name: {{ include "productservice.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "productservice.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
